name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - develop*

jobs:
  build:
    name: Build & Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake g++ libfreetype6-dev libpng-dev libopenal-dev libsndfile1-dev pkg-config libalsa-ocaml-dev libsixel-dev libevdev-dev nlohmann-json3-dev

      - name: Install Build Wrapper
        run: |
          curl -L https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip -o build-wrapper.zip
          unzip build-wrapper.zip
          sudo mv build-wrapper-linux-x86 /opt/build-wrapper

      - name: Compile with Build Wrapper
        run: |
          mkdir -p build
          cd build
          /opt/build-wrapper/build-wrapper-linux-x86-64 --out-dir bw-output cmake ..
          /opt/build-wrapper/build-wrapper-linux-x86-64 --out-dir bw-output make -j$(nproc)

      - name: Run SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=TDL
            -Dsonar.sources=source
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}